pcengine:
  emulator: libretro
  core:     pce
pcenginecd:
  emulator: libretro
  core:     pce
nds:
  emulator: libretro
  core:     melonds
ps2:
  emulator: libretro
  core:     play
jaguar:
  emulator: bigpemu
  core:     bigpemu
