default:
  options:
    video_threaded: true
    smooth: false

mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive
fbneo:
  options:
    frameskip: auto
flash:
  emulator: lightspark
  core:     lightspark
