default:
  options:
    hud_support: true

pcengine:
  emulator: libretro
  core:     pce
pcenginecd:
  emulator: libretro
  core:     pce
nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
quake3:
  emulator: ioquake3
  core:     ioquake3
jaguar:
  emulator: bigpemu
  core:     bigpemu
