default:
  options:
    gfxbackend: gl

3ds:
  emulator: libretro
  core:     panda3ds
nds:
  emulator: libretro
  core:     melondsds
fmtowns:
  emulator: libretro
  core:     mame
atomiswave:
  emulator: libretro
  core:     flycast
dreamcast:
  emulator: libretro
  core:     flycast
naomi:
  emulator: libretro
  core:     flycast
