blank_issues_enabled: false
contact_links:
  - name: REG-Linux feature requests
    url: https://discord.gg/23wJ69eaCh
    about: REG-Linux requests, for emulation and general operating system features
  - name: EmulationStation GUI feature requests
    url: https://discord.gg/23wJ69eaCh
    about: EmulationStation GUI requests, for features in the ES front-end in REG-Linux
  - name: Help and support
    url: https://discord.gg/23wJ69eaCh
    about: For support with using REG-Linux

