default:
  options:
    hud_support: true

pcengine:
  emulator: libretro
  core:     pce
pcenginecd:
  emulator: libretro
  core:     pce
nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
model3:
  emulator: supermodel
  core:     supermodel-legacy
  options:
    videomode: max-720x576
quake3:
  emulator: ioquake3
  core:     ioquake3
  options:
    videomode: max-1280x720
jaguar:
  emulator: bigpemu
  core:     bigpemu
