3ds:
  emulator: libretro
  core:     panda3ds
pcengine:
  emulator: libretro
  core:     pce
pcenginecd:
  emulator: libretro
  core:     pce
nds:
  emulator: libretro
  core:     melonds
fmtowns:
  emulator: libretro
  core:     mame
ps2:
  emulator: libretro
  core:     play
model3:
  emulator: supermodel
  core:     supermodel-legacy
