default:
  options:
    video_threaded: true
    videomode: max-1280x720

amiga500:
  emulator: libretro
  core:     uae4arm
amiga1200:
  emulator: libretro
  core:     uae4arm
amigacd32:
  emulator: libretro
  core:     uae4arm
amigacdtv:
  emulator: libretro
  core:     uae4arm
nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
psx:
  options:
    gpu_software: true
    gfxbackend: Software
atomiswave:
  emulator: libretro
  core:     flycastvl
dreamcast:
  emulator: libretro
  core:     flycastvl
naomi:
  emulator: libretro
  core:     flycastvl
flash:
  emulator: lightspark
  core:     lightspark

