3ds:
  emulator: libretro
  core:     panda3ds
pcengine:
  emulator: libretro
  core:     pce
pcenginecd:
  emulator: libretro
  core:     pce
model3:
  emulator: supermodel
  core:     supermodel-legacy
gamecube:
  emulator: libretro
  core:     dolphin
nds:
  emulator: libretro
  core:     melonds
wii:
  emulator: libretro
  core:     dolphin
fmtowns:
  emulator: libretro
  core:     mame
ps2:
  emulator: libretro
  core:     play
flash:
  emulator: lightspark
  core:     lightspark
jaguar:
  emulator: bigpemu
  core:     bigpemu
