default:
  options:
    video_threaded: true
    smooth: false
    retroarch.menu_driver: xmb
    retroarch.audio_driver: pipewire

3ds:
  emulator: libretro
  core:     panda3ds
nds:
  emulator: libretro
  core:     melonds
fmtowns:
  emulator: libretro
  core:     mame
