## SCANLINES
default:
  # shader affects retroarch shaders
  shader: crt/GritsScanlines
  # scanline affect fba2x
  scanline: true
snes:
  shader: crt/GritsScanlines
nes:
  shader: crt/GritsScanlines
n64:
  shader: crt/GritsScanlines
gba:
  shader: handheld/zfast-lcd
gb:
  shader: handheld/zfast-lcd
gbc:
  shader: handheld/zfast-lcd
fds:
  shader: crt/GritsScanlines
virtualboy:
  shader: crt/GritsScanlines
# Sega
sg1000:
  shader: crt/GritsScanlines
mastersystem:
  shader: crt/GritsScanlines
megadrive:
  shader: crt/GritsScanlines
gamegear:
  shader: handheld/zfast-lcd
sega32x:
  shader: crt/GritsScanlines
segacd:
  shader: crt/GritsScanlines
# Arcade
neogeo:
  shader: crt/GritsScanlines
neogeocd:
  shader: crt/GritsScanlines
mame:
  shader: crt/GritsScanlines
fba:
  shader: crt/GritsScanlines
naomi:
  shader: crt/GritsScanlines
atomiswave:
  shader: crt/GritsScanlines
#
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
gw:
  shader: crt/GritsScanlines
vectrex:
  shader: crt/GritsScanlines
lynx:
  shader: handheld/zfast-lcd
lutro:
  shader: crt/GritsScanlines
wswan:
  shader: handheld/zfast-lcd
wswanc:
  shader: handheld/zfast-lcd
pcengine:
  shader: crt/GritsScanlines
pcenginecd:
  shader: crt/GritsScanlines
supergrafx:
  shader: crt/GritsScanlines
atari800:
  shader: crt/GritsScanlines
atari2600:
  shader: crt/GritsScanlines
atari5200:
  shader: crt/GritsScanlines
atari7800:
  shader: crt/GritsScanlines
prboom:
  shader: crt/GritsScanlines
psx:
  shader: crt/GritsScanlines
colecovision:
  shader: crt/GritsScanlines
# Computers
msx:
  shader: crt/GritsScanlines
msx1:
  shader: crt/GritsScanlines
msx2:
  shader: crt/GritsScanlines
amiga:
  shader: crt/GritsScanlines
amstradcpc:
  shader: crt/GritsScanlines
atarist:
  shader: crt/GritsScanlines
zxspectrum:
  shader: crt/GritsScanlines
o2em:
  shader: crt/GritsScanlines
zx81:
  shader: crt/GritsScanlines
pcfx:
  shader: crt/GritsScanlines
x68000:
  shader: crt/GritsScanlines
